backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\Booking;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        $rules = [];
        if (Yii::$app->user->identity) {
            if (Yii::$app->user->identity->isRole(['root', 'admin', 'booking'])) {
                $rules[] = [
                    'actions' => [],
                    'allow' => true,
                    'roles' => ['@'],
                ];
            }
        }
        $rules[] = [
            'actions' => ['error'],
            'allow' => true,
        ];
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => $rules,
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
//                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'backend\models\ErrorModel',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionCacheFlush()
    {
        Yii::$app->cache->flush();
        Yii::$app->frontendCache->flush();
        Yii::$app->session->setFlash('success', 'Кэш очищен.');
        $this->redirect('index');
    }

    public function actionTask()
    {
        $dateStart = new \DateTime(Yii::$app->request->get('date_start', date('Y-m-d 08:00:00')));
        $dateEnd = new \DateTime(Yii::$app->request->get('date_end', date('Y-m-d 22:00:00')));

        $bookings = Booking::find()->with(['object', 'payments', 'customer'])->where('(date_in >= :dateStart AND date_in <= :dateEnd) OR
            (date_out >= :dateStart AND date_out <= :dateEnd)',
            ['dateStart' => $dateStart->format('Y-m-d H:i:s'), 'dateEnd' => $dateEnd->format('Y-m-d H:i:s')])
            ->andWhere(['approved' => Booking::ENABLE])
            ->all();

        $fmt = new \IntlDateFormatter(
            'ru_RU',
            \IntlDateFormatter::FULL,
            \IntlDateFormatter::FULL,
            Yii::$app->getTimeZone(),
            \IntlDateFormatter::GREGORIAN,
            'HH:mm, dd MMMM'
        );
        $tasks = [];

        foreach ($bookings as $booking) {
            $payments = 0;
            if ($booking->payments) {
                foreach ($booking->payments as $payment) {
                    $payments += $payment->price;
                }
            }

            $task = [
                'id' => 0,
                'time' => '',
                'check_in' => true,
                'apartment' => '<div>' . $booking->object->ob_name . '</div><div>' . $booking->object->address . '</div>',
                'customer' => '<div>' . $booking->customer->name . '</div><div>' . $booking->customer->phone . '</div>',
                'total' => '<div>Оплачено: ' . Yii::$app->formatter->asCurrency($payments) . '</div><div>' .
                    $booking->getAttributeLabel('booking_total') . ': ' .
                    Yii::$app->formatter->asCurrency($booking->booking_total) . '</div>',
                'information' => $booking->information,
            ];

            $dateIn = new \DateTime($booking->date_in);
            $dateOut = new \DateTime($booking->date_out);
            if ($dateIn > $dateStart && $dateIn < $dateEnd) {
                $task['id'] = $dateIn->getTimestamp();
                $task['time'] =  $fmt->format($dateIn);
                $tasks[] = $task;
            }
            if ($dateOut > $dateStart && $dateOut < $dateEnd) {
                $task['id'] = $dateOut->getTimestamp();
                $task['time'] =  $fmt->format($dateOut);
                $task['check_in'] = false;
                $tasks[] = $task;
            }
        }

        if ($tasks) {
            usort($tasks, function ($a, $b) {
                if ($a['id'] === $b['id']) return 0;
                return $a['id'] > $b['id'] ? 1 : -1;
            });
        }

        return $this->render('task', [
            'tasks' => $tasks,
            'dateStart' => $dateStart,
            'dateEnd' => $dateEnd
        ]);
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Apartment;
use common\models\City;
use common\models\Page;
use common\models\Slider;
use Yii;
use frontend\core\BaseController;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class SiteController extends BaseController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    public function actionIndex()
    {
        $apartments = Apartment::find()->with(['apartmentPhotos'])
            ->where([
                'status' => Apartment::STATUS_APPROVED,
                'user_id' => 3,
        ])->orderBy(['position' => 'ASC'])->limit(20)->all();

        $city = Yii::$app->cache->get('site-index-city');
        if ($city === false) {
            $city = City::findOne(['id' => 1]);
            Yii::$app->cache->set('site-index-city', $city, Yii::$app->params['cacheTime']['day']);
        }

        $slider = Yii::$app->cache->get('site-index-slider');
        if ($slider === false) {
            $slider = Slider::find()->onCondition(['status' => 1])->orderBy(['id' => 'asc'])->all();
            Yii::$app->cache->set('site-index-slider', $slider, Yii::$app->params['cacheTime']['day']);
        }

        return $this->render('index', [
            'apartments' => $apartments,
            'city' => $city,
            'slider' => $slider
        ]);
    }

    public function actionPage($alias)
    {
        $page = Yii::$app->cache->get('site-page-' . $alias);
        if ($page === false) {
            $page = Page::findOne(['alias' => $alias]);
            Yii::$app->cache->set('site-page-' . $alias, $page, 3600 * 24);
        }

        if (is_null($page)) {
            throw new NotFoundHttpException(Yii::t('frontend', 'Not Found'));
        }
        return $this->render('page', [
            'page' => $page
        ]);
    }

}

backend/views/site/error.php
<?php

use yii\helpers\Html;
use backend\assets\AppAsset;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        .content-wrapper{
            margin:0;
        }
        .error-page{
            margin-top:5%
        }
    </style>
</head>
<body class="skin-blue sidebar-mini">
<?php $this->beginBody() ?>
    <div class="wrapper">
        <div class="content-wrapper">
            <section class="content">
                <div class="error-page">
                    <h2 class="headline text-yellow"> <?=$exception->statusCode?></h2>
                    <div class="error-content">
                        <h3><i class="fa fa-warning text-yellow"></i> <?= Html::encode($this->title) ?></h3>
                        <p>
                            <?= nl2br(Html::encode($message)) ?><br>
                            Meanwhile, you may <a href="../../index.html">return to dashboard</a> or try using the search form.
                        </p>
                    </div>
                </div>
            </section>
        </div>
    </div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/site/index.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;
$this->title = 'VitaHome';
$this->params['breadcrumbs'] = []
?>
<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-teal">
            <div class="inner">
                <h3>Бронирование</h3>
                <p><?php echo Html::a('Шахматка', ['booking/grid'], ['style' => ['color'=> '#fff']]);?></p>
            </div>
            <div class="icon">
                <i class="fa fa-book"></i>
            </div>
            <?php echo Html::a('Перейти к списку <i class="fa fa-arrow-circle-right"></i>', ['booking/index'],
                ['class' => 'small-box-footer']);?>
        </div>
    </div>
    <?php if(Yii::$app->user->can('admin')):?>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-teal">
            <div class="inner">
                <h3>Кэш сайта</h3>
                <p><?=Html::a('Очистить кэш', ['site/cache-flush'], ['style' => ['color'=> '#fff']]);?></p>
            </div>
            <div class="icon">
                <i class="fa fa-archive"></i>
            </div>
            <?php echo Html::a('<i class="fa fa-arrow-circle-right"></i>', ['#'],
                ['class' => 'small-box-footer']);?>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>Квартиры</h3>
                <p><?php echo Html::a('Добавить новую', ['apartment/create'], ['style' => ['color'=> '#fff']]);?></p>
            </div>
            <div class="icon">
                <i class="fa fa-bed"></i>
            </div>
            <?php echo Html::a('Перейти к списку <i class="fa fa-arrow-circle-right"></i>', ['apartment/index'],
                ['class' => 'small-box-footer']);?>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3>Слайдер</h3>
                <p><?php echo Html::a('Добавить новый', ['slider/create'], ['style' => ['color'=> '#fff']]);?></p>
            </div>
            <div class="icon">
                <i class="fa fa-picture-o"></i>
            </div>
            <?php echo Html::a('Перейти к списку <i class="fa fa-arrow-circle-right"></i>', ['slider/index'],
                ['class' => 'small-box-footer']);?>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-fuchsia">
            <div class="inner">
                <h3>Страницы</h3>
                <p><?php echo Html::a('Добавить новую', ['page/create'], ['style' => ['color'=> '#fff']]);?></p>
            </div>
            <div class="icon">
                <i class="fa fa-file-text-o"></i>
            </div>
            <?php echo Html::a('Перейти к списку <i class="fa fa-arrow-circle-right"></i>', ['page/index'],
                ['class' => 'small-box-footer']);?>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3>Города</h3>
                <p><?php echo Html::a('Добавить новый', ['city/create'], ['style' => ['color'=> '#fff']]);?></p>
            </div>
            <div class="icon">
                <i class="fa fa-building"></i>
            </div>
            <?php echo Html::a('Перейти к списку <i class="fa fa-arrow-circle-right"></i>', ['city/index'],
                ['class' => 'small-box-footer']);?>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>Районы</h3>
                <p><?php echo Html::a('Добавить новый', ['area/create'], ['style' => ['color'=> '#fff']]);?></p>
            </div>
            <div class="icon">
                <i class="fa fa-building-o"></i>
            </div>
            <?php echo Html::a('Перейти к списку <i class="fa fa-arrow-circle-right"></i>', ['area/index'],
                ['class' => 'small-box-footer']);?>
        </div>
    </div>
    <?php endif;?>
</div>

backend/views/site/task.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $tasks array */
/* @var $dateStart \DateTime */
/* @var $dateEnd \DateTime */
/* @var $form yii\widgets\ActiveForm */

$this->title = Yii::t('app', 'Task');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="task-index box box-primary">
    <div class="box-header with-border">
        <?php $form = ActiveForm::begin(['id'=> 'form-task', 'method' => 'get', 'action' => \yii\helpers\Url::to(['site/task'])]);?>
        <div class="row">
            <div class="col-lg-5 col-md-7 col-sm-12 col-xs-12">
                <div class="form-group">
                    <div class="input-group drp-container">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                        <?php
                        echo \kartik\daterange\DateRangePicker::widget([
                            'name' => 'date_range',
                            'value' => $dateStart->format('Y-m-d H:i') . ' - ' . $dateEnd->format('Y-m-d H:i'),
                            'convertFormat' => true,
                            'useWithAddon' => true,
                            'startAttribute' => 'date_start',
                            'endAttribute' => 'date_end',
                            'pluginOptions' => [
                                'timePicker'=>true,
                                'timePickerIncrement'=>30,
                                'timePicker24Hour' => true,
                                'locale' => ['format'=>'Y-m-d H:i']
                            ]
                        ]);
                        ?>
                        <span class="input-group-btn">
                             <button class="btn btn-primary btn-flat" type="submit" title="Показать"><i class="fa fa-eye"></i></button>
                        </span>
                    </div>
                </div>
            </div>
            <div class="col-lg-7 col-md-5 col-sm-12 col-xs-12 text-right">
                <div class="form-group">
                    <div class="btn-group">
                        <?= Html::a('<i class="fa fa-tasks"></i> Сегодня', ['site/task', 'date_start' => date('Y-m-d 08:00'),
                            'date_end' => date('Y-m-d 22:00')], ['class' => 'btn btn-default btn-flat'])?>
                        <?php
                        echo \yii2assets\printthis\PrintThis::widget([
                            'htmlOptions' => [
                                'id' => 'print-block',
                                'btnClass' => 'btn btn-info btn-flat',
                                'btnId' => 'btnPrintThis',
                                'btnText' => 'Печать',
                                'btnIcon' => 'fa fa-print'
                            ],
                            'options' => [
                                'debug' => false,
                                'importCSS' => true,
                                'importStyle' => false,
        //                        'loadCSS' => "path/to/my.css",
                                'pageTitle' => "",
                                'removeInline' => false,
                                'printDelay' => 333,
                                'header' => null,
                                'formValues' => true,
                            ]
                        ]);
                        ?>
                    </div>
                </div>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
    <div id="print-block" class="box-body table-responsive no-padding">
        <table class="table table-bordered table-striped table-tash">
            <tr>
                <th>Время</th>
                <th>Заезд</th>
                <th>Выезд</th>
                <th>Квартира</th>
                <th>Клиент</th>
                <th>Сумма</th>
                <th>Комментарий</th>
                <th class="no-print"></th>
            </tr>
            <?php foreach ($tasks as $task): ?>
                <tr>
                    <td><?= $task['time']?></td>
                    <td><?= $task['check_in'] ? '<i class="fa fa-check text-success"></i>': ''?></td>
                    <td><?= $task['check_in'] ? '' : '<i class="fa fa-remove text-danger"></i>'?></td>
                    <td><?= $task['apartment']?></td>
                    <td><?= $task['customer'] ?></td>
                    <td><?= $task['total'] ?></td>
                    <td>
                        <div class="task-information"><?= $task['information']?></div>
                    </td>
                    <td class="no-print">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default btn-sm btn-flat edit"><i class="fa fa-edit"></i></button>
                            <button type="button" class="btn btn-danger btn-sm btn-flat trash"><i class="fa fa-trash"></i></button>
                        </div>
                    </td>
                </tr>
            <?php endforeach;?>
        </table>
    </div>
</div>

<?php
$this->registerJs(<<<JS
$('.trash').on('click', function() {
   $(this).parents('tr').remove(); 
});
$('.edit').on('click', function() {
    let task = $(this).parents('tr').find('.task-information');
    let text = task.html();
    task.html('<textarea class="form-control" rows=3>' + text + '</textarea>');
    task.find('textarea').focus();
});
$('.task-information').on('focusout', 'textarea', function() {
    let text = $(this).val();
    $(this).parent().html(text);
});
JS
);

?>