common/models/Booking.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "booking".
 *
 * @property int $id
 * @property int $object_id
 * @property string $date_in
 * @property string $date_out
 * @property int $price
 * @property int $total
 * @property int $discount
 * @property int $customer_id
 * @property string $created_at
 * @property double $days
 * @property int $status_id
 * @property string $information
 * @property string $ical_hash
 * @property int $user_id
 * @property double $transfer_in
 * @property double $transfer_out
 * @property double $more_pay
 * @property double $booking_total
 * @property int $approved
 *
 * @property Customer $customer
 * @property Apartment $object
 * @property Status $status
 * @property Payment[] $payments
 */
class Booking extends \yii\db\ActiveRecord
{
    const ENABLE = 1;
    const DISABLE = 0;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'booking';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['object_id', 'status_id', 'user_id', 'date_in', 'date_out', 'price', 'total', 'booking_total', 'customer_id'], 'required'],
            [['object_id', 'status_id', 'user_id', 'customer_id', 'approved'], 'integer'],
            [['days', 'total', 'booking_total', 'transfer_in', 'transfer_out', 'more_pay', 'price'], 'number'],
            [['date_in', 'date_out', 'created_at'], 'safe'],
            [['information'], 'string', 'max' => 500],
            [['ical_hash'], 'string', 'max' => 255],
            [['customer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Customer::className(), 'targetAttribute' => ['customer_id' => 'id']],
            [['object_id'], 'exist', 'skipOnError' => true, 'targetClass' => Apartment::className(), 'targetAttribute' => ['object_id' => 'id']],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => Status::className(), 'targetAttribute' => ['status_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'object_id' => Yii::t('models', 'Object ID'),
            'date_in' => Yii::t('models', 'Date In'),
            'date_out' => Yii::t('models', 'Date Out'),
            'price' => Yii::t('models', 'Price'),
            'total' => Yii::t('models', 'Total'),
            'discount' => Yii::t('models', 'Discount'),
            'customer_id' => Yii::t('models', 'Customer ID'),
            'created_at' => Yii::t('models', 'Created At'),
            'days' => Yii::t('models', 'Days'),
            'status_id' => Yii::t('models', 'Status ID'),
            'information' => Yii::t('models', 'Information'),
            'ical_hash' => Yii::t('models', 'Ical Hash'),
            'user_id' => Yii::t('models', 'User ID'),
            'transfer_in' => Yii::t('models', 'Transfer In'),
            'transfer_out' => Yii::t('models', 'Transfer Out'),
            'more_pay' => Yii::t('models', 'More Pay'),
            'booking_total' => Yii::t('models', 'Booking Total'),
            'approved' => Yii::t('models', 'Approved'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustomer()
    {
        return $this->hasOne(Customer::className(), ['id' => 'customer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getObject()
    {
        return $this->hasOne(Apartment::className(), ['id' => 'object_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(Status::className(), ['id' => 'status_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayments()
    {
        return $this->hasMany(Payment::className(), ['booking_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

}

backend/controllers/BookingController.php
<?php

namespace backend\controllers;

use backend\models\CustomerSearch;
use backend\models\BookingSearch;
use common\models\Apartment;
use common\models\Customer;
use common\models\Booking;
use common\models\Status;
use Yii;
use yii\base\Model;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;


class BookingController extends Controller
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        $rules = [];
        if (Yii::$app->user->identity) {
            if (Yii::$app->user->identity->isRole(['root', 'admin'])) {
                $rules[] = [
                    'actions' => [],
                    'allow' => true,
                    'roles' => ['@'],
                ];
            } elseif (Yii::$app->user->identity->isRole(['booking'])) {
                $rules[] = [
                    'actions' => ['grid'],
                    'allow' => true,
                    'roles' => ['@'],
                ];
            }
        }
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => $rules,
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Booking models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BookingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionGrid()
    {
        $apartments = Apartment::find()->where(['ob_enable' => 1])->orderBy(['ob_name' => SORT_ASC])->all();
        $statuses = Status::find()->where(['approved' => Status::ENABLE])->all();

        return $this->render('grid', [
            'apartments' => $apartments,
            'statuses' => $statuses
        ]);
    }

    public function actionSpecialOffer()
    {
        $apartments = Apartment::find()->where(['ob_enable' => 1])->orWhere(['user_id' => 3])->orderBy(['ob_name' => SORT_ASC])->all();
        if (Yii::$app->request->isPost && Yii::$app->request->post()) {
            $data = Yii::$app->request->post('Apartment');

            foreach ($apartments as $apartment) {
                $apartmentData = $data[$apartment->id] ?? [];
                $apartment->price = $apartmentData['price'] ?? $apartment->price;
                $apartment->discount_price = $apartmentData['discount_price'] ?? $apartment->discount_price;
                $apartment->is_free_now = $apartmentData['is_free_now'] ?? $apartment->is_free_now;
                $apartment->position = $apartmentData['position'] ?? $apartment->position;
                $apartment->up_at = $apartmentData['up_at'] ?? $apartment->up_at;
                $apartment->save();
            }

            return $this->redirect(['booking/special-offer']);
        }

        return $this->render('special-offer', [
            'apartments' => $apartments
        ]);
    }

    /**
     * Displays a single Booking model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Booking model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Booking();

        $post = Yii::$app->request->post();

        if($model->load($post)) {
            if ($model->save()) {
                Yii::$app->session->setFlash('success', Yii::t('app', 'Success create'));
                if (isset($post['btn_create_and_create'])) {
                    return $this->redirect(['create']);
                }
                if (isset($post['btn_create_and_list'])) {
                    return $this->redirect(['index']);
                }
                return $this->redirect(['update', 'id' => $model->id]);
            } else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Error create'));
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Booking model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $post = Yii::$app->request->post();
        if($model->load($post)){
            if ($model->save()) {
                Yii::$app->session->setFlash('success', Yii::t('app', 'Success save'));
                if (isset($post['btn_update_and_list'])) {
                    return $this->redirect(['index']);
                }
                return $this->redirect(['update', 'id' => $model->id]);
            } else{
                Yii::$app->session->setFlash('error', Yii::t('app', 'Error save'));
            }
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Finds the Booking model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Booking the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Booking::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

backend/views/booking/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Modal;

/* @var $this yii\web\View */
/* @var $model common\models\Booking */
/* @var $form yii\bootstrap\ActiveForm */

$apartmets = ArrayHelper::map(\common\models\Apartment::find()->all(), 'id', 'ob_name');
$statuses = ArrayHelper::map(\common\models\Status::find()->all(), 'id', 'name');
$users = ArrayHelper::map(\common\models\User::find()->all(), 'id', 'username');

\kartik\daterange\MomentAsset::register($this);
?>

<div class="box box-primary">
    <?php $form = ActiveForm::begin([
        'layout' => 'horizontal'
    ]);
    ?>
    <div class="box-body">
        <?= Html::activeHiddenInput($model, 'customer_id')?>
        <?= $form->errorSummary($model, ['class' => 'alert alert-danger'])?>
        <div class="col-sm-6">

            <?= $form->field($model, 'object_id')->dropDownList($apartmets) ?>

            <?= $form->field($model, 'status_id')->dropDownList($statuses) ?>

            <div class="form-group field-booking-customer_id">
                <label class="control-label col-sm-3" for="booking-customer_id">Клиент</label>
                <div class="col-sm-6">
                    <div class="input-group">
                        <div id="booking-customer_view" class="form-control child-block-inline">
                            <?php
                            if ($model->customer) {
                                $contact = '<div class="text-muted"><a href="tel:'.$model->customer->phone.'">
                                        <i class="fa fa-phone"></i> '.$model->customer->phone.'</a></div>';
                                echo '<div>' . $model->customer->name . '</div>' . $contact;
                            }
                            ?>
                        </div>
                        <span class="input-group-btn">
                            <button type="button" id="customers-list" data-url="<?= \yii\helpers\Url::to(['customer/list'])?>"
                                    class="btn btn-default btn-flat" title="Выбрать клиента"><i class="fa fa-search"></i> </button>
                        </span>
                    </div>
                </div>
            </div>

            <?= $form->field($model, 'days')->textInput() ?>

            <?= $form->field($model, 'date_in')->widget(\kartik\datetime\DateTimePicker::classname(), [
                'options' => ['placeholder' => 'Выберите дату...'],
                'pluginOptions' => [
                    'autoclose' => true,
                ],
                'pluginEvents' => [
                    'changeDate' => 'function(e) {  formCalculate(); }'
                ]
            ]); ?>

            <?= $form->field($model, 'date_out')->widget(\kartik\datetime\DateTimePicker::classname(), [
                'options' => ['placeholder' => 'Выберите дату...'],
                'pluginOptions' => [
                    'autoclose' => true,
                ],
                'pluginEvents' => [
                    'changeDate' => 'function(e) {  formCalculate();}'
                ]
            ]); ?>


        </div>
        <div class="col-sm-6">
            <?= $form->field($model, 'transfer_in')->textInput() ?>

            <?= $form->field($model, 'transfer_out')->textInput() ?>

            <?= $form->field($model, 'more_pay')->textInput() ?>

            <?= $form->field($model, 'price')->textInput() ?>

            <?= $form->field($model, 'total')->textInput() ?>

            <?= $form->field($model, 'booking_total')->textInput() ?>

            <?= $form->field($model, 'information')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'approved')->checkbox() ?>

            <?= $form->field($model, 'user_id')->dropDownList($users) ?>

            <?php if (!$model->isNewRecord):?>
                <div class="text-muted col-sm-offset-3">Добавлено: <?= Yii::$app->formatter->asDatetime($model->created_at)?></div>
            <?php endif;?>
        </div>
    </div>
    <div class="box-footer">
        <?php if($model->isNewRecord): ?>
            <?= Html::submitButton('<i class="fa fa-save"></i> ' . Yii::t('app', 'CreateEdit'),
                ['class' => 'btn btn-success btn-flat', 'name' => 'btn_create_and_edit']) ?>
            <?= Html::submitButton('<i class="fa fa-save"></i> <i class="fa fa-list"></i> ' . Yii::t('app', 'CreateList'),
                ['class' => 'btn btn-success btn-flat', 'name' => 'btn_create_and_list']) ?>
            <?= Html::submitButton('<i class="fa fa-plus-circle"></i> ' . Yii::t('app', 'CreateCreate'),
                ['class' => 'btn btn-success  btn-flat', 'name' => 'btn_create_and_create']) ?>
        <?php else: ?>
            <?= Html::submitButton('<i class="fa fa-save"></i> ' . Yii::t('app', 'Save'),
                ['class' => 'btn btn-primary btn-flat', 'name' => 'btn_update_and_edit']) ?>
            <?= Html::submitButton('<i class="fa fa-save"></i> <i class="fa fa-list"></i> ' . Yii::t('app', 'SaveList'),
                ['class' => 'btn btn-primary btn-flat', 'name' => 'btn_update_and_list']) ?>
        <?php endif; ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

<?php

Modal::begin([
    'id' => 'modal',
    'header' => 'Выбор клиента',
    'size' => 'modal-lg',
]);

    echo '<div id="modal-content"><div style="text-align:center"><img src="/images/loader.gif"></div></div>';

Modal::end();


$this->registerJs(<<<JS
 $('#customers-list').click(function () {
        $('#modal')
            .modal('show')
            .find('#modal-content')
            .load($(this).data('url'));
    });

$('.modal-content').on('click', '.customer-select', function() {
  $('#booking-customer_id').val($(this).data('id'));
  $('#booking-customer_view').html($(this).parents('tr').find('.customer-name').html());
  $('#modal').modal('hide');
});
    $('#booking-price').on('keyup', function () {
        formCalculatePayment();
    });
    $('#booking-transfer_in').on('keyup', function () {
        formCalculatePayment();
    });
    $('#booking-transfer_out').on('keyup', function () {
        formCalculatePayment();
    });
    $('#booking-more_pay').on('keyup', function () {
        formCalculatePayment();
    });
    $('#booking-days').on('keyup', function () {
        formCalculatePayment();
    });

    function formCalculate() {
        formCalculateDays();
        formCalculatePayment();
    }

    function formCalculateDays() {
        let sDate = moment($('#booking-date_in').val()),
            eDate = moment($('#booking-date_out').val()),
            days;
        days = getRangeDateDays(sDate.valueOf(), eDate.valueOf());
        if (days <= 0) days = 1;
        $('#booking-days').val(days);
    }

    function formCalculatePayment() {
        $('#booking-total').val($('#booking-days').val() * $('#booking-price').val());
        $('#booking-booking_total').val(parseInt($('#booking-total').val()) + parseInt($('#booking-transfer_in').val()) + 
        parseInt($('#booking-transfer_out').val()) + parseInt($('#booking-more_pay').val()));
    }
    
    function getRangeDateDays(date1, date2) {
        date1 = new Date(date1);
        date1.setHours(0, 0, 0, 0);
        date2 = new Date(date2);
        date2.setHours(0, 0, 0, 0);
        var days = Math.floor((date2.getTime() - date1.getTime()) / (3600000 * 24));
        return days;
    }
JS
);
?>

backend/views/booking/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model backend\models\BookingSearch */
/* @var $form yii\widgets\ActiveForm */

$objects = ArrayHelper::map(\common\models\Apartment::find()->all(), 'id', 'ob_name');
$statuses = ArrayHelper::map(\common\models\Status::find()->all(), 'id', 'name');
$users = \common\models\User::dropList();
?>

<?php $this->beginContent('@backend/views/layouts/blocks/_search.php',
    ['filterActive' => (bool)Yii::$app->request->get('BookingSearch')]); ?>
        <?php $form = ActiveForm::begin([
            'action' => ['index'],
            'method' => 'get',
            'options' => [
                'data-pjax' => 1
            ],
        ]); ?>

        <div class="row">
            <div class="col-md-3 col-sm-4">
                <?= $form->field($model, 'id') ?>
            </div>
            <div class="col-md-3 col-sm-4">
                <?= $form->field($model, 'object_id')->dropDownList($objects, ['prompt' => Yii::t('yii', '(not set)')]) ?>
            </div>
            <div class="col-md-3 col-sm-4">
                <?= $form->field($model, 'status_id')->dropDownList($statuses, ['prompt' => Yii::t('yii', '(not set)')]) ?>
            </div>
            <div class="col-md-3 col-sm-4">
                <?= $form->field($model, 'user_id')->dropDownList($users, ['prompt' => Yii::t('yii', '(not set)')]) ?>
            </div>
            <div class="col-md-3 col-sm-4">
                <?= $form->field($model, 'customer_id') ?>
            </div>
            <div class="col-md-3 col-sm-4">
                <?= $form->field($model, 'approved')->dropDownList(Yii::$app->params['yesNo'], ['prompt' => Yii::t('yii', '(not set)')]) ?>
            </div>
            <div class="col-md-3 col-sm-4">
            </div>
        </div>

        <div class="form-group">
            <?= Html::submitButton('<i class="fa fa-search"></i> ' . Yii::t('backend', 'Search'), ['class' => 'btn btn-primary btn-flat']) ?>
            <?= Html::a('<i class="fa fa-refresh"></i> ' . Yii::t('backend', 'Reset'), ['/booking/index'], ['class' => 'btn btn-default btn-flat']) ?>
        </div>
        <?php ActiveForm::end(); ?>

<?php $this->endContent() ?>

backend/views/booking/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Booking */

$this->title = Yii::t('app', 'Create');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Bookings'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="customer-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/booking/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel backend\models\BookingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend', 'Bookings');
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="box box-primary">
    <?php Pjax::begin(); ?>
    <div class="box-header with-border">
        <h3 class="box-title"><?=$this->title?></h3>
        <div class="box-tools">
            <?= Html::a('<i class="fa fa-plus"></i> ' . Yii::t('backend', 'Create'), ['create'], ['class' => 'btn btn-sm btn-default btn-flat']) ?>
        </div>
    </div>
    <div class="box-body no-padding">
        <?= $this->render('_search', ['model' => $searchModel]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'layout' => '<div class="table-responsive">{items}</div><div class="padding-md clearfix"><div class="pull-left">{summary}</div>{pager}</div>',
            'pager' => ['options' => ['class' => 'pagination pagination-sm no-margin pull-right']],
            'columns' => [
                'id',
                [
                    'attribute' => 'object_id',
                    'format' => 'raw',
                    'value' => function($model) {
                        return $model->object ? $model->object->ob_name : Yii::t('app', '(not set)');
                    }
                ],
                [
                    'attribute' => 'status_id',
                    'format' => 'raw',
                    'value' => function($model) {
                        return $model->status ? '<span class="label" style="background-color: ' .
                            $model->status->color . '">' . $model->status->name . '</span>' :
                            Yii::t('app', '(not set)');
                    }
                ],
                [
                    'attribute' => 'customer_id',
                    'format' => 'raw',
                    'value' => function($model) {
                        $guest = '<div>' . $model->getAttributeLabel('customer_id') . ': ' . ($model->customer ?
                            $model->customer->name : Yii::t('app', '(not set)')) . '</div>';
                        return $guest . '<div class="text-muted">' . Yii::$app->formatter->asDatetime($model->date_in) .
                            ' - ' . Yii::$app->formatter->asDatetime($model->date_out). '</div>';
                    }
                ],
                [
                    'attribute' => 'price',
                    'format' => 'raw',
                    'value' => function($model) {
                        $price = '<div>' . $model->days . ' * ' . Yii::$app->formatter->asCurrency($model->price) .
                            ' = ' . Yii::$app->formatter->asCurrency($model->total) . '</div>';
                        $bookingTotal = '<div>' . $model->getAttributeLabel('booking_total') . ': ' .
                            Yii::$app->formatter->asCurrency($model->booking_total) . '</div>';
                        return $price . $bookingTotal;
                    }
                ],
                'information',
                [
                    'attribute' => 'approved',
                    'format' => 'raw',
                    'value' => function($model) {
                        return  $model->approved ? '<i class="fa fa-check text-success"></i> ' :
                            '<i class="fa fa-times text-danger"></i> ';
                    }
                ],
                [
                    'attribute' => 'created_at',
                    'format' => 'raw',
                    'value' => function($model) {
                        $user = '<div>' . $model->getAttributeLabel('user_id') . ': ' . ($model->user ?
                            $model->user->username : Yii::t('app', '(not set)')) . '</div>';
                        return $user . '<div>' . Yii::$app->formatter->asDatetime($model->created_at) . '</div>';
                    }
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{view} {update}'
                ],
            ],
        ]); ?>
    </div>
    <?php Pjax::end(); ?>
</div>

backend/views/booking/special-offer.php
<?php

use yii\widgets\ActiveForm;
use wbraganca\dynamicform\DynamicFormWidget;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\ApartmentSearch */
/* @var $apartments common\models\Apartment */
/* @var $status common\models\Status */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Специальные предложения';
$this->params['breadcrumbs'][] = $this->title;

?>

<?php $form = ActiveForm::begin([
    'options' => ['enctype'=>'multipart/form-data'],
    'id' => 'apartment-form'
]); ?>
<div class="box box-solid">
    <div class="box-body">
        <div id="x-window" class="x_panel">
            <div id="x-alert"></div>
            <div class="x-grid-body">
                <div id="x-grid-items">
                    <div class="x-grid-header x-grid-items-header">
                        <table class="x-grid-table-header">
                            <tr><td>№</td><td>Квартира</td></tr>
                        </table>
                    </div>
                    <div class="x-grid-items-body">
                        <?php foreach($apartments as $value):?>
                            <div class="x-grid-block-body x-grid-block-body2">
                                <div class="x-grid-apartment-name" title="3:  - 10000" data-toggle="tooltip">
                                    №<?=$value->id?>:  - <?=$value->price?>&nbsp;тенге
                                    <div class="text-muted"><?= $value->address ?></div>
                                </div>
                            </div>
                        <?php endforeach;?>
                    </div>
                </div>
                <div id="x-grid-cells">
                    <div class="x-grid-header x-grid-cells-header">
                        <div class="x-table-header2">
                            <div class="x-table-header2-title">Цена</div>
                            <div class="x-table-header2-title">Цена со скидкой</div>
                            <div class="x-table-header2-title">Свободно сейчас</div>
                            <div class="x-table-header2-title">Позиция на главной</div>
                            <div class="x-table-header2-title">Поднятие</div>
                        </div>
                    </div>
                    <div class="x-grid-cells-body">
                        <?php foreach($apartments as $value):?>
                            <div class="x-grid-table-rows2" >
                                <div class="x-grid-table-rows2-item">
                                    <?= $form->field($value, '[' . $value->id . ']price')->textInput(['type' => 'number'])->label(false) ?>
                                </div>
                                <div class="x-grid-table-rows2-item">
                                    <?= $form->field($value, '[' . $value->id . ']discount_price')->textInput(['type' => 'number'])->label(false) ?>
                                </div>
                                <div class="x-grid-table-rows2-item">
                                    <?= $form->field($value, '[' . $value->id . ']is_free_now')->checkbox(['label' => ''])->label(false) ?>
                                </div>
                                <div class="x-grid-table-rows2-item">
                                    <?= $form->field($value, '[' . $value->id . ']position')->textInput(['type' => 'number'])->label(false) ?>
                                </div>
                                <div class="x-grid-table-rows2-item">
                                    <?= $form->field($value, '[' . $value->id . ']up_at')->widget(\kartik\datetime\DateTimePicker::classname(), [
                                        'options' => ['placeholder' => 'Выберите дату...'],
                                        'pluginOptions' => [
                                            'autoclose' => true,
                                        ]
                                    ])->label(false); ?>
                                </div>
                            </div>
                        <?php endforeach;?>
                    </div>
                </div>
            </div>
        </div>
        <p></p>
        <p class="text-right">
            <?= Html::submitButton('<i class="fa fa-save"></i> ' . \Yii::t('backend', 'Save'),
                ['class' => 'btn btn-success', 'name' => 'btn_create_and_edit']) ?>
        </p>
    </div>
</div>
<?php ActiveForm::end(); ?>

backend/views/booking/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Booking */

$this->title = Yii::t('app', 'Update: {name}', [
    'name' => $model->id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Bookings'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>

<div class="customer-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>