backend/controllers/ApartmentController.php
<?php

namespace backend\controllers;

use backend\base\Model;
use common\models\ApartmentPhoto;
use common\models\Ical;
use Gregwar\Image\Image;
use Yii;
use common\models\Apartment;
use backend\models\ApartmentSearch;
use yii\db\Exception;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * ApartmentController implements the CRUD actions for Apartment model.
 */
class ApartmentController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['error'],
                        'allow' => true,
                    ],
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Apartment models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ApartmentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Apartment model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Apartment();
        $post = Yii::$app->request->post();
        if($model->load($post)) {
            $model->updated_at = $model->created_at = date('Y-m-d H:i:s');
            if ($model->save()) {
                Yii::$app->session->setFlash('success', \Yii::t('backend', 'Success create'));
                if (isset($post['btn_create_and_create'])) {
                    return $this->redirect(['create']);
                }
                if (isset($post['btn_create_and_list'])) {
                    return $this->redirect(['index']);
                }
                return $this->redirect(['update', 'id' => $model->id]);
            } else {
                Yii::$app->session->setFlash('error', \Yii::t('backend', 'Error create'));
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Apartment model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelsIcal = $model->icals;

        $post = Yii::$app->request->post();
        if($model->load($post)){
            $oldIDs = ArrayHelper::map($modelsIcal, 'id', 'id');
            $modelsIcal = Model::createMultiple(Ical::classname(), $modelsIcal);
            Model::loadMultiple($modelsIcal, Yii::$app->request->post());
            $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($modelsIcal, 'id', 'id')));

            // validate all models
            $valid = $model->validate();
            $valid = Model::validateMultiple($modelsIcal) && $valid;

            if ($valid) {
                $transaction = Yii::$app->db->beginTransaction();
                try {
                    if ($flag = $model->save(false)) {
                        if (!empty($deletedIDs)) {
                            Ical::deleteAll(['id' => $deletedIDs]);
                        }
                        foreach ($modelsIcal as $modelIcal) {
                            $modelIcal->apartment_id = $model->id;
                            $modelIcal->last_update = date('Y-m-d H:i:s');
                            if (! ($flag = $modelIcal->save(false))) {
                                $transaction->rollBack();
                                break;
                            }
                        }
                    }
                    if ($flag) {
                        $transaction->commit();
                        Yii::$app->session->setFlash('success', Yii::t('app', 'Success save'));
                        if (isset($post['btn_update_and_list'])) {
                            return $this->redirect(['index']);
                        }
                        return $this->redirect(['update', 'id' => $model->id]);
                    } else {
                        Yii::$app->session->setFlash('error', Yii::t('app', 'Error save'));
                    }
                } catch (Exception $e) {
                    $transaction->rollBack();
                }
            }
        }

        return $this->render('update', [
            'model' => $model,
            'modelsIcal' => (empty($modelsIcal)) ? [new Ical()] : $modelsIcal
        ]);
    }

    /**
     * Deletes an existing Apartment model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if($this->findModel($id)->delete()){
            Yii::$app->session->setFlash('success', \Yii::t('backend', 'Success delete'));
        }

        return $this->redirect(['index']);
    }

    public function actionPhotodelete($id){
        $model = ApartmentPhoto::findOne($id);
        $apartmentId = $model->apartment_id;
        @unlink(Yii::$app->params['uploadOrig'] . $apartmentId . '/' . $model->name);
        @unlink(Yii::$app->params['uploadLarge'] . $apartmentId . '/' . $model->name);
        @unlink(Yii::$app->params['uploadSmall'] . $apartmentId . '/' . $model->name);
        $model->delete();
        Yii::$app->session->setFlash('success', \Yii::t('backend', 'Success save'));
        return $this->redirect(['update', 'id' => $apartmentId]);
    }

    public function actionPosition(){
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $result = [];
        if (Yii::$app->request->isAjax) {
            $data = Yii::$app->request->post();
            /**
             * @var $model \common\models\Apartment
             */
            $model = Apartment::find()->with('apartmentPhotos')->where(['id' => $data['id']])->one();
            foreach ($model->apartmentPhotos as $photo) {
                foreach($data['position'] as $key=>$value){
                    if($value == $photo->id){
                        $photo->position = $key;
                        $photo->save();
                        continue;
                    }
                }
            }

            $result = [
                'code' => 100,
            ];
        }
        return $result;
    }

    /**
     * Finds the Apartment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Apartment the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Apartment::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

frontend/controllers/ApartmentController.php
<?php

namespace frontend\controllers;

use common\models\Apartment;
use frontend\core\BaseController;
use yii\web\NotFoundHttpException;

class ApartmentController extends BaseController
{
    public function actionIndex($id)
    {
        $apartment = Apartment::find()
            ->with(['apartmentPhotos', 'city'])
            ->where('id = :id', [
                ':id' => $id
            ])
            ->one();

        if (is_null($apartment)) {
            throw new NotFoundHttpException(\Yii::t('frontend', 'Not Found'));
        }

        if ($apartment->city->id == 1 && $apartment->expired_at < date('Y-m-d H:i:s')) {
            throw new NotFoundHttpException(\Yii::t('frontend', 'Not Found'));
        }

        return $this->render('index', [
            'apartment' => $apartment
        ]);
    }

}

backend/views/apartment/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\City;
use common\models\Area;
use dektrium\user\models\User;
use wbraganca\dynamicform\DynamicFormWidget;

/* @var $this yii\web\View */
/* @var $model common\models\Apartment */
/* @var $form yii\widgets\ActiveForm */

$this->registerJsFile('https://api-maps.yandex.ru/2.1/?lang=ru_RU');
$coords = explode(',', $model->maps);
$x = 0;
if(isset($coords[0])){
    if(is_numeric($coords[0])){
        $x = $coords[0];
    }
}
$y = 0;
if(isset($coords[1])) {
    if(is_numeric($coords[1])){
        $y = $coords[1];
    }
}
$this->registerJs('
ymaps.ready(function(){
	map = new ymaps.Map ("map",{center:[' . ($x?:'51.128422') . ',' . ($y?:'71.430564') . '],zoom:14},{});
	map.events.add("click", function (e) {
            var coords = e.get("coords");
            $("#apartment-maps").val(coords[0].toPrecision(8)+","+coords[1].toPrecision(8));
            map.balloon.open(coords, {
                contentHeader: "Установлена метка",
                contentBody:
                    "<p>Координаты на карте: " + [
                        coords[0].toPrecision(8),
                        coords[1].toPrecision(8)
                    ].join(", ") + "</p>"
            });

        });

    var x = ' . $x . ', y = ' . $y . ';
    if(x != 0 && y != 0){
        map.balloon.open([x, y],{
            contentBody: "<p>Координаты на карте: " + [x, y].join(",") + "</p>"
        });
    }
});
$(function() {
    $( "#sortable" ).sortable({
        connectWith: "#sortable",
        opacity: 0.8,
        stop: function(event, ui) {
            var k = 0;
            var pos_photo = [];
            $("ul#sortable li.ui-state-default").each(function(){
                pos_photo[k] = $(this).data("id");
                k++;
            });
            $.ajax({
                type: "POST",
                url: "'.\yii\helpers\Url::toRoute(['apartment/position']).'",
                data: {"id": '.($model->isNewRecord ? 0: $model->id).', "position": pos_photo},
                cache: false
            }).done(function (data) {
                $(\'#photo-success\').html(\'\');

                if(data.code === 100){
                    $(\'#photo-success\').html(\'<div class="alert alert-success">Позиция фотографии изменена.</div>\');
                } else{
                    $(\'#photo-alert\').html(\'<div class="alert alert-danger">Не удалось изменить позицию фотографии.</div>\');
                }
            }).fail(function() {
                alert( "Ошибка!!! Не удалось изменить позицию фотографий." );
            });
        }
    });
    $( "#sortable" ).disableSelection();
  });
');
$this->registerCss('
.photo-delete{display:block;color: red;}
.photo-delete:hover{opacity: .8;color:red;}
#sortable { list-style-type: none; margin: 0; padding: 0; width: 100%; }
#sortable li { margin: 3px 3px 3px 0; padding: 1px; float: left; text-align: center; }
');

?>
<div class="box box-primary">
<?php $form = ActiveForm::begin([
    'options' => ['enctype'=>'multipart/form-data'],
    'id' => 'apartment-form'
]); ?>
    <div class="box-body">
        <div class="row">
            <div class="col-sm-6">

                <?= $form->field($model, 'price')->textInput() ?>
                <?= $form->field($model, 'discount_price')->textInput() ?>
                <?= $form->field($model, 'is_free_now')->checkbox() ?>
                <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'text')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-sm-6">

                <?= $form->field($model, 'city_id')->dropDownList(City::allCities()) ?>

                <?= $form->field($model, 'area_id')->dropDownList(Area::allAreas()) ?>
                <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>

                <?= $form->field($model, 'floor')->textInput() ?>

                <?= $form->field($model, 'floor_total')->textInput() ?>

                <?= $form->field($model, 'room')->textInput() ?>

                <?= $form->field($model, 'square')->textInput() ?>

                <?= $form->field($model, 'sleep')->textInput(['maxlength' => true]) ?>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-6">
                <?= $form->field($model, 'status')->dropDownList($model->getStatusList()) ?>
                <?= $form->field($model, 'user_id')->dropDownList(\yii\helpers\ArrayHelper::map(User::find()
                    ->asArray()
                    ->orderBy('username')
                    ->all(), 'id', 'username')) ?>

                <?= $form->field($model, 'up_at')->widget(\kartik\datetime\DateTimePicker::classname(), [
                    'options' => ['placeholder' => 'Выберите дату...'],
                    'pluginOptions' => [
                        'autoclose' => true,
                    ]
                ]); ?>

                <?= $form->field($model, 'expired_at')->widget(\kartik\datetime\DateTimePicker::classname(), [
                    'options' => ['placeholder' => 'Выберите дату...'],
                    'pluginOptions' => [
                        'autoclose' => true,
                    ]
                ]); ?>


                <?php if(!$model->isNewRecord): ?>
                    <div class="callout callout-info">
                        <p><strong>Создано:</strong> <?=$model->created_at?></p>
                        <p><strong>Последнее обновление:</strong> <?=$model->updated_at?></p>
                    </div>
                <?php endif; ?>
            </div>
            <div class="col-sm-6">
                <?= $form->field($model, 'ob_enable')->checkbox() ?>
                <?= $form->field($model, 'position')->textInput() ?>
                <?= $form->field($model, 'ob_name')->textInput(['maxlength' => true]) ?>
                <?php if ($model->ical_hash):?>
                    <div class="form-group field-apartment-position required">
                        <label class="control-label" for="ical_hash">Адрес в формате iCal</label>
                        <input type="text" id="ical_hash" class="form-control" name="ical_hash"  onfocus="this.select()" readonly="readonly"
                               value="<?= \yii\helpers\Url::to(['/calendar/ical', 'id' => $model->ical_hash], true)?>" autocomplete="offe">
                        <p class="help-block help-block-error "></p>
                    </div>
                <?php endif;?>
            </div>
        </div>

        <div class="padding-v-md">
            <div class="line line-dashed"></div>
        </div>
        <?php
        $statuses = \common\models\Status::dropList();
        DynamicFormWidget::begin([
            'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
            'widgetBody' => '.container-items', // required: css class selector
            'widgetItem' => '.item', // required: css class
            'limit' => 4, // the maximum times, an element can be cloned (default 999)
            'min' => 0, // 0 or 1 (default 1)
            'insertButton' => '.add-item', // css class
            'deleteButton' => '.remove-item', // css class
            'model' => $modelsIcal[0],
            'formId' => 'apartment-form',
            'formFields' => [
                'title',
                'ical_url',
                'status_id',
                'approved',
            ],
        ]); ?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-calendar"></i> Импорт календарей
                <button type="button" class="pull-right add-item btn btn-success btn-xs"><i class="fa fa-plus"></i> Добавить</button>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body container-items"><!-- widgetContainer -->
                <?php foreach ($modelsIcal as $index => $modelIcal): ?>
                    <div class="item panel panel-default"><!-- widgetBody -->
                        <div class="panel-heading">
                            <span class="panel-title">Календарь</span>
                            <button type="button" class="pull-right remove-item btn btn-danger btn-xs"><i class="fa fa-minus"></i></button>
                            <div class="clearfix"></div>
                        </div>
                        <div class="panel-body">
                            <?php
                            // necessary for update action.
                            if (!$modelIcal->isNewRecord) {
                                echo Html::activeHiddenInput($modelIcal, "[{$index}]id");
                            }
                            ?>
                            <div class="row">
                                <div class="col-sm-6">
                                    <?= $form->field($modelIcal, "[{$index}]title")->textInput(['maxlength' => true]) ?>
                                    <?= $form->field($modelIcal, "[{$index}]ical_url")->textInput(['maxlength' => true]) ?>
                                </div>
                                <div class="col-sm-6">
                                    <?= $form->field($modelIcal, "[{$index}]status_id")->dropDownList($statuses) ?>
                                    <?= $form->field($modelIcal, "[{$index}]approved")->checkbox() ?>
                                </div>
                            </div><!-- end:row -->

                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php DynamicFormWidget::end(); ?>

        <?= $form->field($model, 'maps')->hiddenInput(['maxlength' => true]) ?>

        <div id="map" style="width: 100%; height: 400px; margin-bottom:10px"></div>

        <?= $form->field($model, 'photos[]')->fileInput(['multiple' => true, 'accept' => 'image/*']) ?>

        <div class="row" style="margin-bottom:10px">
            <div class="col-md-12">
                <p><strong>Фотографии:</strong></p>
                <div id="photo-success"></div>
                <?php
                if($model->apartmentPhotos){
                    echo '<ul id="sortable">';
                    foreach($model->apartmentPhotos as $value) {

                        echo '<li class="ui-state-default" data-position="'.$value->position.'" data-id="'.$value->id.'">' .
                            Html::a(Html::img('/images/apartments/small/' . $model->id . '/' . $value->name, ['width' => '200']),
                                '/uploads/apartments/' . $model->id . '/' . $value->name, ['target' => '_blank']) .
                            Html::a('<i class="fa fa-close"></i> удалить', ['photodelete', 'id'=>$value->id], [
                                'class' => 'photo-delete',
                                'title' => "Удалить",
                                'aria-label' => "Удалить",
                                'data-confirm' => "Вы уверены, что хотите удалить этот элемент?"
                            ]) .
                            '</li>';
                    }
                    echo '</ul>';
                }else{
                    echo '<div  class="callout callout-warning"><p>Нет загруженных фотографий</p></div>';
                }
                ?>
            </div>
        </div>
    </div>

    <div class="box-footer">
        <?php if($model->isNewRecord): ?>
            <?= Html::submitButton('<i class="fa fa-save"></i> ' . \Yii::t('backend', 'CreateEdit'),
                ['class' => 'btn btn-success', 'name' => 'btn_create_and_edit']) ?>
            <?= Html::submitButton('<i class="fa fa-save"></i> <i class="fa fa-list"></i> ' . \Yii::t('backend', 'CreateList'),
                ['class' => 'btn btn-success', 'name' => 'btn_create_and_list']) ?>
            <?= Html::submitButton('<i class="fa fa-plus-circle"></i> ' . \Yii::t('backend', 'CreateCreate'),
                ['class' => 'btn btn-success', 'name' => 'btn_create_and_create']) ?>
        <?php else: ?>
            <?= Html::submitButton('<i class="fa fa-save"></i> ' . \Yii::t('backend', 'Save'),
                ['class' => 'btn btn-primary', 'name' => 'btn_update_and_edit']) ?>
            <?= Html::submitButton('<i class="fa fa-save"></i> <i class="fa fa-list"></i> ' . \Yii::t('backend', 'SaveList'),
                ['class' => 'btn btn-primary', 'name' => 'btn_update_and_list']) ?>
        <?php endif; ?>
    </div>
<?php ActiveForm::end(); ?>

</div>

backend/views/apartment/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model backend\models\ApartmentSearch */
/* @var $form yii\widgets\ActiveForm */

$users = \common\models\User::dropList();

?>
<?php $this->beginContent('@backend/views/layouts/blocks/_search.php',
    ['filterActive' => (bool)Yii::$app->request->get('ApartmentSearch')]); ?>

        <?php $form = ActiveForm::begin([
            'action' => ['index'],
            'method' => 'get',
            'options' => [
                'data-pjax' => 1
            ],
        ]); ?>

        <div class="row">
            <div class="col-md-3 col-sm-4">
                <?= $form->field($model, 'id') ?>
            </div>
            <div class="col-md-3 col-sm-4">
                <?= $form->field($model, 'name') ?>
            </div>
            <div class="col-md-3 col-sm-4">
                <?= $form->field($model, 'address') ?>
            </div>
            <div class="col-md-3 col-sm-4">
                <?= $form->field($model, 'user_id')->dropDownList($users, ['prompt' => Yii::t('yii', '(not set)')]) ?>
            </div>
            <div class="col-md-3 col-sm-4">
                <?= $form->field($model, 'city_id')->dropDownList(\common\models\City::allCities(), ['prompt' => Yii::t('yii', '(not set)')]) ?>
            </div>
            <div class="col-md-3 col-sm-4">
                <?= $form->field($model, 'status')->dropDownList(\common\models\Apartment::getStatusList(), ['prompt' => Yii::t('yii', '(not set)')]) ?>
            </div>
            <div class="col-md-3 col-sm-4">
            </div>
        </div>

        <div class="form-group">
            <?= Html::submitButton('<i class="fa fa-search"></i> ' . Yii::t('backend', 'Search'), ['class' => 'btn btn-primary btn-flat']) ?>
            <?= Html::a('<i class="fa fa-refresh"></i> ' . Yii::t('backend', 'Reset'), ['/apartment/index'], ['class' => 'btn btn-default btn-flat']) ?>
        </div>
        <?php ActiveForm::end(); ?>
<?php $this->endContent() ?>

backend/views/apartment/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Apartment */

$this->title = 'Создать';
$this->params['breadcrumbs'][] = ['label' => 'Квартиры', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

backend/views/apartment/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\ApartmentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Квартиры';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box box-primary">
    <?php Pjax::begin(); ?>
    <div class="box-header with-border">
        <h3 class="box-title"><?=$this->title?></h3>
        <div class="box-tools">
            <?= Html::a('<i class="fa fa-plus"></i> ' . Yii::t('backend', 'Create'), ['create'], ['class' => 'btn btn-sm btn-default btn-flat']) ?>
        </div>
    </div>
    <div class="box-body no-padding">

        <?php  echo $this->render('_search', ['model' => $searchModel]); ?>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'layout' => '<div class="table-responsive">{items}</div><div class="padding-md clearfix"><div class="pull-left">{summary}</div>{pager}</div>',
            'pager' => ['options' => ['class' => 'pagination pagination-sm no-margin pull-right']],
            'columns' => [
                [
                    'attribute' => 'id',
                    'format' => 'raw',
                    'label' => Yii::t('models', 'Name'),
                    'value' => function ($model) {
                        return Html::a($model->id . ' - ' . $model->name, ['apartment/update', 'id' => $model->id]);
                    }
                ],
                [
                    'attribute' => 'price',
                    'value' => function($model){
                        return Yii::$app->formatter->asCurrency($model->price);
                    }
                ],
                [
                    'attribute' => 'status',
                    'format' => 'raw',
                    'value' => function($model){
                        return $model->getStatusLabel();
                    }
                ],
                'address',
                [
                    'attribute' => 'city_id',
                    'format' => 'raw',
                    'value' => function ($model) {
                        return $model->city ? Html::a($model->city->name, ['city/update', 'id' => $model->city_id]) : Yii::t('app', '(not set)');
                    }
                ],
                [
                    'attribute' => 'user_id',
                    'format' => 'raw',
                    'value' => function ($model) {
                        return $model->user ? Html::a($model->user->username, ['/user/profile/show', 'id' => $model->user_id]) : Yii::t('app', '(not set)');
                    }
                ],
                [
                    'attribute' => 'updated_at',
                    'format' => 'raw',
                    'value' => function($model) {
                        return Yii::$app->formatter->asDatetime($model->updated_at);
                    }
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{update} {delete}',
                ],
            ],
        ]); ?>
    </div>
    <?php Pjax::end(); ?>
</div>

backend/views/apartment/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Apartment */

$this->title = \Yii::t('backend', 'UpdateObject', $model->name);
$this->params['breadcrumbs'][] = ['label' => 'Квартиры', 'url' => ['index']];
$this->params['breadcrumbs'][] = \Yii::t('backend', 'Update');
?>

    <?= $this->render('_form', [
        'model' => $model,
    'modelsIcal' => $modelsIcal
    ]) ?>